# Generated by Django 4.1.3 on 2022-11-16 08:27

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceItem',
            fields=[
                ('cl_itemid', models.CharField(default=users.models.get_default_id, max_length=20, primary_key=True, serialize=False)),
                ('studid', models.CharField(blank=True, max_length=9, null=True)),
                ('sem', models.CharField(blank=True, max_length=1, null=True)),
                ('sy', models.CharField(blank=True, max_length=9, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolve', models.BooleanField(blank=True, default='False', null=True)),
                ('resolve_date', models.DateField(blank=True, null=True)),
                ('resolve_by', models.CharField(blank=True, max_length=8, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=8, null=True)),
                ('record_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'clearance_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=200)),
                ('office_head', models.CharField(blank=True, max_length=8, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('office_parent', models.CharField(blank=True, max_length=50, null=True)),
                ('deptlogo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'office',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_desc', models.TextField(blank=True, null=True)),
                ('trans_recorded', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction_log',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='userid',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='ClearingOffice',
            fields=[
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.office')),
                ('staff', models.TextField(blank=True, null=True)),
                ('office_serial', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clearing_office',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='officeid',
            field=models.ForeignKey(blank=True, db_column='officeid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.office'),
        ),
    ]
