# Generated by Django 4.1.3 on 2022-11-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clearanceitem_office_transactionlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarViews',
            fields=[
                ('cl_itemid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('office_id', models.CharField(blank=True, max_length=50, null=True)),
                ('studid', models.CharField(blank=True, max_length=9, null=True)),
                ('studfullname', models.CharField(blank=True, max_length=100, null=True)),
                ('collcode', models.CharField(blank=True, max_length=4, null=True)),
                ('resolve', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
